#!/usr/bin/env bash

pushd () {
  command pushd "$@" > /dev/null
}

popd () {
  command popd "$@" > /dev/null
}

status () {
  command echo "****** $1 ******"
}

build_priv-apk () {
  apktool -q b -c -p temp/framedir/ temp/lenok-$1/
  pushd temp/lenok-$1/dist/
  zipalign -fp 4 $1.apk $1-aligned.apk
  mv $1-aligned.apk $1.apk
  popd
  cp temp/lenok-$1/dist/$1.apk extract/lenok/priv-app/$1/$1.apk
  chown root:root extract/lenok/priv-app/$1/$1.apk
}


status "lenok2dory patcher started!"
echo
status "This uses sudo and may require your password"

# export PATH=$BUILD_DIR/prebuilt:$PATH

echo
status "Cleaning up..."
echo
rm -rf temp/
rm -Rf extract

echo
status "Extracting images..."
echo
mkdir -p extract
sudo unsquashfs -d extract/dory images/dory/system.img
sudo unsquashfs -d extract/lenok images/lenok/system.img

echo
status "Cleaning lenok's system..."
echo

pushd extract/lenok/
rm recovery-from-boot.p
rm bin/{install-recovery.sh,irsc_util,sensors.qcom,subsystem_ramdump,wpa_supplicant}
rm -Rf etc/{firmware/,recovery-resource.dat,sensors/sensor_def_lenok.conf,wifi/}
rm -Rf etc/permissions/{android.hardware.sensor.barometer.xml,android.hardware.sensor.heartrate.xml,android.hardware.wifi.xml}
rm lib/hw/*lenok.so

pushd vendor/lib/
rm -rf ../firmware hw/ libAKM8963.so libdiag.so libdsutils.so libidl.so libmdmdetect.so libqmi* libsensor1.so \
  libsensor_reg.so libsensor_user_cal.so
popd

popd


echo
status "Decompiling lenok's resources, please wait..."
echo
apktool -q if -p temp/framedir/ extract/lenok/framework/framework-res.apk
apktool -q d -f -o temp/lenok-framework-res/ extract/lenok/framework/framework-res.apk
apktool -q d -f -o temp/lenok-services/ extract/lenok/framework/services.jar
apktool -q d -f -p temp/framedir/ -o temp/lenok-OEMSetup/ extract/lenok/priv-app/OEMSetup/OEMSetup.apk
apktool -q d -s -f -p temp/framedir/ -o temp/lenok-SettingsProvider/ extract/lenok/priv-app/SettingsProvider/SettingsProvider.apk
apktool -q d -s -f -p temp/framedir/ -o temp/lenok-ClockworkAmbient/ extract/lenok/priv-app/ClockworkAmbient/ClockworkAmbient.apk
apktool -q d -s -f -p temp/framedir/ -o temp/lenok-ClockworkSettings/ extract/lenok/priv-app/ClockworkSettings/ClockworkSettings.apk

echo
status "Patching lenok's system..."
echo

cp patch/media/bootanimation.zip extract/lenok/media/
chown root:root extract/lenok/media/bootanimation.zip

patch -p0 -l -i patch/dory.patch
# Disable checking certs for shared system apps
# Because framework-res.apk is app with shared user id, system checks its signature anyway. Let's avoid this behavior
patch -p0 -l < patch/shared-certs.patch
sed -i "/\b\(ro.build.expect.bootloader\|ro.expect.recovery_id\)\b/d" extract/lenok/build.prop
cp patch/product_image.png temp/lenok-OEMSetup/res/drawable-hdpi-v4/

build_priv-apk SettingsProvider
build_priv-apk ClockworkAmbient
build_priv-apk ClockworkSettings
build_priv-apk OEMSetup

apktool -q b -c temp/lenok-framework-res/
pushd temp/lenok-framework-res/dist/
zipalign -fp 4 framework-res.apk framework-res-aligned.apk
mv framework-res-aligned.apk framework-res.apk
popd
cp temp/lenok-framework-res/dist/framework-res.apk extract/lenok/framework/framework-res.apk
chown root:root extract/lenok/framework/framework-res.apk

apktool -q b -c temp/lenok-services/
pushd temp/lenok-services/dist/
zipalign -fp 4 services.jar services-aligned.jar
mv services-aligned.jar services.jar
popd
cp temp/lenok-services/dist/services.jar extract/lenok/framework/services.jar
chown root:root extract/lenok/framework/services.jar

pushd extract/
rm lenok/build.prop.orig

cp -a dory/bin/batteryd lenok/bin/
cp -a dory/etc/audioservice.conf lenok/etc/
cp -a dory/etc/regulatory_info.png lenok/etc/
cp -ar dory/etc/sensors/ lenok/etc/
# cp -a dory/lib/libhardware_legacy.so lenok/lib/
# ^^^ WARNING!!! FIX ME!!! ^^^
cp -a dory/lib/libinvensense_hal.so lenok/lib/
cp -a dory/lib/libmllite.so lenok/lib/
cp -a dory/lib/libmplmpu.so lenok/lib/
cp -a dory/lib/hw/audio.primary.dory.so lenok/lib/hw/
cp -a dory/lib/hw/lights.dory.so lenok/lib/hw/
cp -a dory/lib/hw/lis3dsh_tilt.so lenok/lib/hw/
cp -a dory/lib/hw/power.dory.so lenok/lib/hw/
cp -a dory/lib/hw/sensors.dory.so lenok/lib/hw/
cp -a dory/lib/hw/sensors.invensense.so lenok/lib/hw/
# cp -a dory/media/bootanimation.zip lenok/media/
cp -ar dory/vendor/firmware/ lenok/vendor/
popd


echo
status "Making system image..."
echo
# env "PATH=$PATH" mksquashfsimage.sh extract/lenok system4dory.img -s -m /system -c file_contexts
./prebuilt/mksquashfs extract/lenok/ system4dory.img -comp lz4 -b 131072 -no-exports -noappend -no-fragments -no-duplicates \
  -android-fs-config -context-file file_contexts -mount-point /system
chmod 777 system4dory.img

echo
status "Done!"
